// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqvO6mkC_jPGCkHWwbYFiiMilZqwYR0g8',
    appId: '1:115596712226:web:385d5178762fdb983a6d7b',
    messagingSenderId: '115596712226',
    projectId: 'mapmypath-a2dcf',
    authDomain: 'mapmypath-a2dcf.firebaseapp.com',
    storageBucket: 'mapmypath-a2dcf.firebasestorage.app',
    measurementId: 'G-MM6KBV9V9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfKu3lAWfakhG1Hy6ccA_0F-7Tpdvo03k',
    appId: '1:115596712226:android:e24aed3c5d9f21ac3a6d7b',
    messagingSenderId: '115596712226',
    projectId: 'mapmypath-a2dcf',
    storageBucket: 'mapmypath-a2dcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8E2M8lcK0kv9k1VP_AtgwlyCVVPEvbNE',
    appId: '1:115596712226:ios:432269aef3c95fb93a6d7b',
    messagingSenderId: '115596712226',
    projectId: 'mapmypath-a2dcf',
    storageBucket: 'mapmypath-a2dcf.firebasestorage.app',
    iosBundleId: 'com.buytoday.mapmypathapp',
  );
}
